setup:
  random_state: 42
  n_jobs: -1

file:
  online: True
  root: 'data'

data:
  max_len: 100000
  add_random_noise: True
  delete_outlier: True
  outlier_lower_limit: 0.001  
  outlier_upper_limit: 0.999

split:
  n_splits: 4

shap:
  max_num: 1000

importance:
  sort: True
  normalize: True

simulation:
  num: 100