setup:
  random_state: 42
  n_jobs: 1

file:
  root: "data"

data:
  max_len: 100000
  add_random_noise: True

split:
  n_splits: 4

shap:
  max_num: 1000

importance:
  sort: True
  normalize: True

simulation:
  num: 100